version: 0.0
os: linux
files:
   - source: /web
     destination: /var/www/html
permissions:
   - object: /var/www/html
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/install_apache.sh
      runas: ec2-user
    - location: scripts/start_apache.sh
      runas: ec2-user
   AfterInstall:
    - location: scripts/restart_apache.sh
      runas: ec2-user
